### PR TITLE
Upgrade to use LoopBack 3.x

### PR DESCRIPTION
**Pull request by Amir-61**
* Upgrade to use LoopBack 3.x

/to: @0candy @superkhau

### CODE REVIEW

**Comment by 0candy** [comment]
@Amir-61 You need to update server config files as well. Also, this example has five step branches. You need to update everything. Please check with @superkhau

**Comment by Amir-61** [comment]
>@Amir-61 You need to update server config files as well.

Actually I think server/config.json already looks good:
 It has:
```
"context": false,
```
and 
```
"handleErrors": false
```

> Also, this example has five step branches. You need to update everything. Please check with @superkhau

I need more clarification for this please... 

@superkhau Could you give more info?

**Comment by 0candy** [comment]
Sorry, I meant tags not branches.

**Comment by Amir-61** [comment]
Related to https://github.com/strongloop-internal/loopback-knowledge-base/pull/116

**Comment by Amir-61** [comment]
Closing this PR as based on this KB-PR: https://github.com/strongloop-internal/loopback-knowledge-base/pull/116, we need to reimplement `loopback-getting-started` from scratch (0 code) in a separate branch; for more info please see https://github.com/strongloop-internal/loopback-knowledge-base/pull/116#discussion_r87239385

Created task: https://github.com/strongloop-internal/scrum-loopback/issues/1151

**Comment by pthieu** [comment]
PR closed because it was discussed it's not the correct way to do this.

**Pull request closed without merging**
