### PR TITLE
Fixes typo in README.md

### PR DESCRIPTION
**Pull request by benjamin-albert**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@benjamin-albert , thanks for submitting the PR.  Could you please sign the CLA?  https://cla.strongloop.com/agreements/strongloop/loopback-getting-started  
Thanks!

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@benjamin-albert , could you please sign the CLA (link provided above)?  Without it being signed, we cannot accept your change and have to close the PR.  Thanks!!

**Comment by benjamin-albert** [comment]
@dhmlau Sorry for not getting back sooner. I signed the CLA.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
sorry.. The PR is out of date. could you please rebase?

**Comment by dhmlau** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
@benjamin-albert Ty for the typo fix! :tada:

**Pull request merged**
