### PR TITLE
Tests with memory as ds

### PR DESCRIPTION
**Pull request by cgole**

### CODE REVIEW

**Comment by cgole** [comment]
not merging yet. I have to change the datasource back to mysql

**Comment by rmg** [comment]
If these tests can pass using an in-memory connector then they should also work with a blank mysql database. If so, it should be possible to use the localhost database available in our CI environment. Just check `process.env.MYSQL_USER` and `process.env.MYSQL_PASSWORD` to get the credentials.

**Comment by cgole** [comment]
@rmg, this example by default uses mysql as DS. So the credentials are already in the datasource config.

**Comment by cgole** [comment]
@raymondfeng @superkhau  I think there is a bug in mysql PUT.  The test is failing because of that. I tried it manually and verified that it is a bug

**Comment by rmg** [comment]
Using that datasource as-is means these tests are not safe to run in parallel. Running them sequentially will make them take literally 8x longer. That's why I suggested using the server provided by the CI environment instead of sharing an external database.

**Comment by bajtos** [comment]
@cgole what's the status of this work? Are you still keen to get it finished?

**Comment by superkhau** [comment]
@cgole I suggest simply writing simpler smoke tests to ensure CI is running the tests. Something along the lines of:

```
var assert = require('assert');

describe('smoke test', function() {
  it('should pass', function() {
    assert(1, 1);
  });
});
```

That should be good enough to see if CI is running the tests properly without complicating the test case and/or requiring more involved code reviews. Then on the LB team can then deal with the writing of unit/functional tests).

@bajtos Thoughts?

**Comment by bajtos** [comment]
> That should be good enough to see if CI is running the tests properly without complicating the test case and/or requiring more involved code reviews. Then on the LB team can then deal with the writing of unit/functional tests).

@superkhau @cgole The tests created by Chandrika looks mostly good to me and since we have too many other tasks on our plates, I think it may be better to help Chandrika to get this done instead of trying to write a new test suite ourselves. That assumes Chandrika has time to keep working on this pull request.

If we decide that the tests should be added by developers, then I'd rather not add any dummy smoke tests like `assert(1, 1)` and wait with no test suite until we have time to write some real tests.

**Comment by superkhau** [comment]
>The tests created by Chandrika looks mostly good to me and since we have too many other tasks on our plates, I think it may be better to help Chandrika to get this done instead of trying to write a new test suite ourselves. That assumes Chandrika has time to keep working on this pull request.

I'm fine with the tests currently, but I was talking about adding tests to other projects in the future.

>If we decide that the tests should be added by developers, then I'd rather not add any dummy smoke tests like assert(1, 1) and wait with no test suite until we have time to write some real tests.

It is my understanding that her purpose is not to test our apps, but to make sure CI is simply running them properly.

Let's take this getting started for example. There are tests that see if the app is up and running, etc, but IMO those tests just confuse the subject. They should be testing the things we add in each step of the documentation. ie. We add a model, write a test to see if the model is returning the correct properties, check if the rest api is serving up properly, etc. We should correspond the test writing in conjunction with the documentation instructions in those cases (so new users know WHY we have extra test files in the project).

The developer who wrote the app should be writing the tests because they understand the domain. In this case it's quite simple so it doesn't really matter, but I reviewed the CI tests for other projects and they are irrelevant to the domain (ie. Just adding tests that aren't related to the example topics doesn't help IMO). In those cases I'd rather have a simple smoke test as a stub to let us know this needs proper testing instead of a test suite that isn't related.

**Comment by superkhau** [comment]
>If we decide that the tests should be added by developers, then I'd rather not add any dummy smoke tests like assert(1, 1) and wait with no test suite until we have time to write some real tests.

It already had no test suite for over a year now and now we're adding tests that aren't relevant and not updating the documentation instructions to explain why. It just feels like we're adding more dirt/maintenance IMO.

**Comment by bajtos** [comment]
> Let's take this getting started for example. There are tests that see if the app is up and running, etc, but IMO those tests just confuse the subject. They should be testing the things we add in each step of the documentation. ie. We add a model, write a test to see if the model is returning the correct properties, check if the rest api is serving up properly, etc. We should correspond the test writing in conjunction with the documentation instructions in those cases (so new users know WHY we have extra test files in the project).

> The developer who wrote the app should be writing the tests because they understand the domain. In this case it's quite simple so it doesn't really matter, but I reviewed the CI tests for other projects and they are irrelevant to the domain (ie. Just adding tests that aren't related to the example topics doesn't help IMO). In those cases I'd rather have a simple smoke test as a stub to let us know this needs proper testing instead of a test suite that isn't related.

Excellent point! I agree the tests in example repos should be an integral part of the creation process described in the documentation.

I personally prefer no tests over smoke tests like `assert(1,1)`.

> It already had no test suite for over a year now and now we're adding tests that aren't relevant and not updating the documentation instructions to explain why. It just feels like we're adding more dirt/maintenance IMO.

Agreed. I am proposing to close this pull request and create a new story to redo this properly, so that we can plan the work into a future sprint.

@cgole @superkhau thoughts?

**Comment by superkhau** [comment]
>I personally prefer no tests over smoke tests like assert(1,1).

I agree with this, however I believe for @cgole to test whether the CI infrastructure on the devops side is working properly, she needs to run at least one test (preferably the simplest possible to get the job done). Which is the whole reasoning for the smoke test (the simple assert(1,1)). Under normal circumstance, I would just say write a simple test using request that pings `localhost:3000` to see if the app is running. However, since we write both apps and libraries, this wouldn't work for libs. In fact, we should probably have one standardized test file specifically for CI.

```test/ci.test.js
var assert = require('assert');

describe('ci infrastructure', function() {
  it('should run this test', function() {
    assert(true);
  });
});
```

This would be a bit more descriptive as to why the test is there at all in the first place.

>Agreed. I am proposing to close this pull request and create a new story to redo this properly, so that we can plan the work into a future sprint.

+1 for this. IMO the next story we create should just be "Create standard test for CI infrastructure". And the task is one simple PR, write the aforementioned test to ensure CI can run tests via `npm test`.

**Comment by bajtos** [comment]
I am closing this PR per the conversation above. @superkhau could you please create a new GH issue if you think it's important to follow up on this work?

**Comment by superkhau** [comment]
>@superkhau could you please create a new GH issue if you think it's important to follow up on this work?

Let's just reference this issue if and when devops needs to test whether CI works with a particular project. I suggest we do it on an "as needed" basis.

**Pull request closed without merging**
